name: Invite Me Action

on:
  issue_comment:
    types: [created]

jobs:
  check-invite:
    runs-on: ubuntu-latest
    steps:
      - name: Check if the comment is on the correct issue and contains "invite me"
        if: |
          github.event.issue.number == 5 && contains(github.event.comment.body, 'invite me')
        run: |
          echo "Invite request detected on Issue #5!"

          COMMENTER_USER="${{ github.event.comment.user.login }}"
          
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -X POST \
               -d '{"body": "Thank you, @'"$COMMENTER_USER"'! We have received your invite request, and we will send you an invite soon."}' \
               "https://api.github.com/repos/${{ github.repository }}/issues/5/comments"

          echo "Invite request for $COMMENTER_USER processed on Issue #5."
